eureka:
  client:
    register-with-eureka: true
    fetch-registry: true # Connect with EUREKA SERVER
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS}
  instance:
    hostname: ${HOSTNAME}.eureka
    

#Use for local deployment

#eureka:
 # client:
 #  register-with-eureka: true
 #  fetch-registry: true # Connect with EUREKA SERVER
 #  service-url:
  #    defaultZone: http://localhost:8761/eureka
  #instance:
   # hostname: localhost
    
#-------OWN PROPERTIES------#

##--------DATABASE--------##
postgresurl: jdbc:postgresql://localhost:5432

##--------AZURE--------##
tenantid: ec1ae248-6fcc-43a1-bc2b-88d4fc381227

