eureka:
  client:
    register-with-eureka: true
    fetch-registry: true # Connect with EUREKA SERVER
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
postgresurl: jdbc:postgresql://localhost:5432
tentantid: ec1ae248-6fcc-43a1-bc2b-88d4fc381227

