#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true # Connect with EUREKA SERVER
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS}
#  instance:
#    preferIpAddress: true
#    hostname: ${HOSTNAME}
    

#Use for local deployment

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true # Connect with EUREKA SERVER
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
#-------OWN PROPERTIES------#

##--------DATABASE--------##
postgresurl: jdbc:postgresql://localhost:5432
DB_HOST: localhost
DB_NAME: v1nd
POSTGRES_USER: postgres

##--------AZURE--------##
TENANT_ID: ec1ae248-6fcc-43a1-bc2b-88d4fc381227

